### ISSUE TITLE
Sources behind the listener sound muffled, and it is difficult to tell that it is supposed to be behind

### ISSUE THREAD

**Issue by Neurrone** [resonance-audio/resonance-audio#13]
Hi,

When a sound is behind the listener, it sounds muffled and it is difficult to tell that it is supposed to be behind you.

This is an [audio sample of this](https://www.dropbox.com/s/uztw5vjtsy9air3/resonance%20sample.zip?dl=1). The file contains the same source, moving counterclockwise in a unit circle around the listener using 3 different audio libraries: Resonance Audio, Oculus spatializer and Steam Audio. The positioning of the other 2 libraries for sources behind you is much better.

**Comment by mgorzel** [comment]
Hey @Neurrone, the differences are likely due to different HRTFs used in each database. RA uses KU100 set from the SADIE database. If the 'source behind' doesn't work well for you, It is possible that this particular set isn't suitable for you (although we found that it works well for most of the people, not all obviously).

**Comment by Neurrone** [comment]
Thanks @mgorzel for the info.
