### ISSUE TITLE
How to use Occulusion

### ISSUE THREAD

**Issue by Ono-Sendai** [resonance-audio/resonance-audio#55]
In the Fundamental Concepts section you mention occlusion: https://resonance-audio.github.io/resonance-audio/discover/concepts.html

How is this supposed to be used in practice?

The only relevant API call seems to be SetSoundObjectOcclusionIntensity.

Is the expectation that the 'occlusion intensity' is computed by the client code, and passed to Resonance?

I could compute this by ray tracing between the sound source and the listener position and checking for occluders, is that what you had in mind?

Thanks!

**Comment by anokta** [comment]
That is indeed the case. Since ResonanceAudioApi does not have any information regarding the underlying geometric representation of a sound object, the occlusion feature is left abstract to be controlled directly by the client.

FYI, there is an example implementation of a trivial point source based computation in the Unity integration code that can be used for reference:  https://github.com/resonance-audio/resonance-audio/blob/a1e1c75f7000387faea337ae3fb3f9e69a796dbb/platforms/unity/UnityIntegration/Assets/ResonanceAudio/Scripts/ResonanceAudio.cs#L178

**Comment by Ono-Sendai** [comment]
Cool.  I just tried out the raytracing technique, seemed to work pretty well: https://twitter.com/SubstrataVr/status/1443767385635262471
