### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by ghost** [resonance-audio/resonance-audio#6]
Dear all,
trying to compile this project for unity. Downloaded CMake, Git, Mercurial and Visual Studio 2015. I am working on Windows 10 x64.

Cloned the repository and executed:
./$YOUR_LOCAL_REPO/third_party/clone_core_deps.sh
./$YOUR_LOCAL_REPO/third_party/clone_build_install_unity_deps.sh

Then tried to compile with ./build.sh -t=UNITY_PLUGIN
But getting the following error

unity_win.def : error LNK2001: unresolved external symbol SetRt60ValuesAndProxyRoomProperties [.\$YOUR_LOCAL_REPO\build\platforms\unity\audiopluginresonanceaudio.vcxproj]
.\$YOUR_LOCAL_REPO/build/platforms/unity/Release/audiopluginresonanceaudio.lib : fatal error LNK1120: 1 unresolved externals [.\$YOUR_LOCAL_REPO\build\platforms\unity\audiopluginresonanceaudio.vcxproj]
Compiling project ".\$YOUR_LOCAL_REPO\build\platforms\unity\audiopluginresonanceaudio.vcxproj" (default target) NOT COMPLETED.
Compiling project ".\$YOUR_LOCAL_REPO\build\ALL_BUILD.vcxproj" (default target) NOT COMPLETED.
Compiling project ".\$YOUR_LOCAL_REPO\build\install.vcxproj" (default target) NOT COMPLETED.

Compiling NOT SUCCEDED.

".\$YOUR_LOCAL_REPO\build\install.vcxproj" (default target) (1) ->
".\$YOUR_LOCAL_REPO\build\ALL_BUILD.vcxproj" (default target) (3) ->
".\$YOUR_LOCAL_REPO\build\platforms\unity\audiopluginresonanceaudio.vcxproj" (default target) (9) ->
(destination: Link) ->
  unity_win.def : error LNK2001: unresolved external symbol SetRt60ValuesAndProxyRoomProperties [.\$YOUR_LOCAL_REPO\build\platforms\unity\audiopluginresonanceaudio.vcxproj]
  .\$YOUR_LOCAL_REPO/build/platforms/unity/Release/audiopluginresonanceaudio.lib : fatal error LNK1120: 1 unresolved externals [.\$YOUR_LOCAL_REPO\build\platforms\unity\audiopluginresonanceaudio.vcxproj]

Thanks and regards,
Daniel Pinardi

**Comment by anokta** [comment]
Ah good catch! Seems like one function definition managed to escape from the legacy code. :) 

Should be fixed now via 0dec4c0. Could you try again and verify if it resolves the linking issue?

**Comment by ghost** [comment]
Verified and, yes, now it works !

Sorry, can I ask a very last question?
I was expecting to get directly the ResonanceAudioForUnity.unitypackage 
Could you briefly explain me how to do or where find instruction ?

**Comment by anokta** [comment]
Great to hear!

The artifacts of the build are populated in the _install_ folder as a full Unity project, which basically will be the combination of the compiled library and the Unity assets that are copied from the corresponding [UnityIntegration](https://github.com/resonance-audio/resonance-audio/tree/master/platforms/unity/UnityIntegration) folder. At that point, there are mainly two alternatives you can go for to create the _.unitypackage_:

1. The easiest option is to simply open the generated Unity project in the Editor, and select the _ResonanceAudio_ folder in the project assets to export a Unity package.
2. Alternatively, in order to automate the process, you can write a simple command line script (e.g., in Python) that runs Unity through command line without the need of opening the Editor manually. Please see [the corresponding Unity documentation here](https://docs.unity3d.com/Manual/CommandLineArguments.html) for reference (**-exportPackage** option is the one to look for). Also, feel free to contribute back to the repo if you get such a script working, so everyone can benefit! :)
